doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        logging: '%kernel.debug%'
        options:
            1002: "SET time_zone = 'UTC'"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            calendar:
                class: App\DoctrineFilter\CalendarFilter
            expense:
                class: App\DoctrineFilter\ExpenseFilter
        dql:
            datetime_functions:
                date: DoctrineExtensions\Query\Mysql\Date
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
