lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_id_claim: email
    token_ttl: 600

when@test:
    lexik_jwt_authentication:
        secret_key: '%kernel.project_dir%/config/jwt/test/private-test.pem'
        public_key: '%kernel.project_dir%/config/jwt/test/public-test.pem'
        pass_phrase: 'test'