monolog:
    channels:
        - deprecation
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 14
            channels: ['!event']
        deprecation:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.deprecation.log'
            max_files: 14
            channels: [deprecation]

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: php://stderr
                level: info
                channels: ['!event']
